monitoring:
  items:
    - SystemMonitor:
    - MemoryMonitor:
    - DiskMonitor:
    - ServerInfo:
        show_ip: true
        iface: eth0
    - ContainerMonitor:
    - TemperatureMonitor:
    - KubernetesMonitor:
  delay: 5
